version: '3.8'

services:
  openshutter:
    image: openshutter:latest
    container_name: openshutter-prod
    network_mode: host
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=4000
      # MongoDB URI should be set in .env.production to point to external MongoDB
      # For same server: MONGODB_URI=mongodb://localhost:27017/openshutter
      # For different server: MONGODB_URI=mongodb://your-mongodb-host:27017/openshutter
      # For MongoDB Atlas: MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/openshutter
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  openshutter-network:
    driver: bridge
