version: '3.8'

services:
  openshutter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openshutter
    ports:
      - "4000:4000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - openshutter-network

networks:
  openshutter-network:
    driver: bridge
