packages:
  - frontend
  - backend

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tensorflow/tfjs-node'
  - canvas
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
