// frontend/src/lib/page-builder/modules/AlbumGallery/config.ts
export const albumGalleryConfig = {
	type: 'albumView',
	label: 'Album view',
	description: 'Album page cards for sub-albums, photos, or both.',
	fields: [
		{ key: 'title', type: 'multilangText', label: 'Title', required: false },
		{ key: 'description', type: 'multilangHTML', label: 'Description', required: false },
		{
			key: 'albumHeaderFieldOrder',
			type: 'list',
			label: 'Album header field order',
			default: ['albumTitle', 'albumDescription', 'albumStats']
		},
		{ key: 'showAlbumPageTitle', type: 'boolean', label: 'Show album page title', default: true },
		{ key: 'showAlbumPageDescription', type: 'boolean', label: 'Show album page description', default: true },
		{ key: 'showAlbumPageStats', type: 'boolean', label: 'Show album page stats', default: true },
		{ key: 'showAlbumHero', type: 'boolean', label: 'Show album hero section', default: false },
		{ key: 'albumSource', type: 'select', label: 'Albums source', options: ['root', 'featured', 'selected', 'current'], default: 'root' },
		{ key: 'selectedAlbums', type: 'albumPicker', label: 'Selected albums', required: false },
		{ key: 'showTitle', type: 'boolean', label: 'Show title (legacy/global)', default: true },
		{ key: 'showAlbumTitle', type: 'boolean', label: 'Show album title', default: true },
		{ key: 'showPhotoTitle', type: 'boolean', label: 'Show photo title', default: true },
		{ key: 'showCover', type: 'boolean', label: 'Show cover image', default: true },
		{ key: 'coverAspect', type: 'select', label: 'Cover aspect', options: ['video', 'square', 'portrait'], default: 'video' },
		{ key: 'showDescription', type: 'boolean', label: 'Show description (legacy/global)', default: true },
		{ key: 'showAlbumDescription', type: 'boolean', label: 'Show album description', default: true },
		{ key: 'showPhotoDescription', type: 'boolean', label: 'Show photo description', default: true },
		{ key: 'descriptionLines', type: 'number', label: 'Description lines', default: 2 },
		{ key: 'cardFieldOrder', type: 'list', label: 'Card field order (legacy/global)', default: ['cover', 'title', 'description', 'photoCount', 'featuredBadge'] },
		{
			key: 'albumCardLayout',
			type: 'select',
			label: 'Album card layout',
			options: ['stack', 'row'],
			default: 'stack',
			description: 'Stack: image on top. Row: thumbnail left, details right (one album per row).',
		},
		{
			key: 'albumCard',
			type: 'select',
			label: 'Album card style',
			options: ['auto', 'bare', 'cards', 'list', 'portrait', 'overlay', 'compact'],
			default: 'auto',
			description:
				'Theme tokens: bare (Noir), cards (Studio), list (Atelier), portrait, overlay, compact. Auto uses pack + layout. Legacy keys (e.g. bareSquare) still work if stored.',
		},
		{
			key: 'photoCard',
			type: 'select',
			label: 'Photo grid style',
			options: [
				'auto',
				'default',
				'square-tight',
				'landscape',
				'portrait',
				'masonry',
				'justified',
				'large-preview',
			],
			default: 'auto',
			description:
				'Theme tokens: square-tight (Noir), landscape (Studio), portrait (Atelier). Justified uses row layout + JS. Auto uses pack default.',
		},
		{ key: 'albumCardFieldOrder', type: 'list', label: 'Album card field order', default: ['cover', 'title', 'description', 'photoCount', 'featuredBadge'] },
		{ key: 'photoCardFieldOrder', type: 'list', label: 'Photo card field order', default: ['cover', 'title', 'description', 'featuredBadge'] },
		{ key: 'showPhotoCount', type: 'boolean', label: 'Show photo count', default: true },
		{ key: 'showFeaturedBadge', type: 'boolean', label: 'Show featured badge (legacy/global)', default: true },
		{ key: 'showAlbumFeaturedBadge', type: 'boolean', label: 'Show album featured badge', default: true },
		{ key: 'showPhotoFeaturedBadge', type: 'boolean', label: 'Show photo featured badge', default: true },
		{
			key: 'cardDataType',
			type: 'select',
			label: 'Card data type',
			options: ['subAlbums', 'photos', 'both'],
			default: 'both'
		},
		{ key: 'mixedDisplayMode', type: 'select', label: 'Mixed display mode', options: ['grouped', 'interleaved'], default: 'grouped' },
		{ key: 'showSectionLabels', type: 'boolean', label: 'Show section labels', default: true },
		{
			key: 'showHeading',
			type: 'boolean',
			label: 'Show grid section heading',
			default: true,
			description: 'When false, hides labels such as "Sub-albums" above the grid. Overrides section label visibility when set.',
		},
		{ key: 'sortBy', type: 'select', label: 'Sort by', options: ['manual', 'order', 'name', 'photoCount', 'createdAt', 'lastPhotoDate'], default: 'manual' },
		{ key: 'sortDirection', type: 'select', label: 'Sort direction', options: ['asc', 'desc'], default: 'asc' },
		{ key: 'limit', type: 'number', label: 'Maximum items', default: 12 },
	],
} as const;
