name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch/tag) to deploy"
        required: false
        default: "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0+sha512.486ebc259d3e999a4e8691ce03b5cac4a71cbeca39372a9b762cb500cfdf0873e2cb16abe3d951b1ee2cf012503f027b98b6584e4df22524e0c7450d9ec7aa7b

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (standalone)
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/dummy
          NEXTAUTH_SECRET: dummy-secret
          NEXTAUTH_URL: https://example.com
        run: pnpm build

      - name: Package artifact
        run: |
          tar -czf release.tgz \
            .next/standalone \
            .next/static \
            public \
            next.config.js \
            package.json \
            env.example

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "release.tgz"
          target: "${{ secrets.DEPLOY_DIR || '~/apps/openshutter' }}"
          timeout: 120s
          command_timeout: 120s

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          envs: DEPLOY_DIR
          script: |
            set -e
            echo "SSH connection successful! Testing deployment..."
            echo "Deployment test - $(date)" > /tmp/openshutter-deploy-test.txt
            echo "Test file created at /tmp/openshutter-deploy-test.txt"
            APP_DIR="${DEPLOY_DIR:-$HOME/apps/openshutter}"
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"
            tar -xzf release.tgz || tar -xzf "$HOME/apps/openshutter/release.tgz"
            rm -f release.tgz "$HOME/apps/openshutter/release.tgz"

            # If DEPLOY_DIR is different, sync files to target
            # No separate SRC_DIR now; extracted directly into APP_DIR

            # Create runtime env file if not exists
            if [ ! -f "$APP_DIR/.env" ]; then
              echo "Create .env on server based on required keys" >&2
              sudo touch "$APP_DIR/.env"
              sudo chown "$USER":"$USER" "$APP_DIR/.env"
            fi

            # Create systemd service if missing
            SERVICE_FILE=/etc/systemd/system/openshutter.service
            if [ ! -f $SERVICE_FILE ]; then
              {
                echo "[Unit]"
                echo "Description=OpenShutter"
                echo "After=network.target"
                echo ""
                echo "[Service]"
                echo "Type=simple"
                echo "WorkingDirectory=$APP_DIR"
                echo "EnvironmentFile=$APP_DIR/.env"
                echo "ExecStart=/usr/bin/node $APP_DIR/.next/standalone/server.js -p 4000"
                echo "Restart=always"
                echo "RestartSec=5"
                echo ""
                echo "[Install]"
                echo "WantedBy=multi-user.target"
              } | sudo tee $SERVICE_FILE > /dev/null
              sudo systemctl daemon-reload
              sudo systemctl enable openshutter
            fi

            # Restart service
            sudo systemctl restart openshutter
