# OpenShutter production setup (Windows)
# Installs production dependencies and creates environment files.
# Run from the extracted deployment folder (same level as backend/ and frontend/).

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

function Read-Default {
    param([string]$Prompt, [string]$Default)
    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

function Encode-MongoPassword {
    param([string]$Password)
    $map = @{
        '!' = '%21'; '@' = '%40'; '#' = '%23'; '$' = '%24'; '%' = '%25'
        '&' = '%26'; '/' = '%2F'; ':' = '%3A'
    }
    $encoded = $Password
    foreach ($key in $map.Keys) {
        $encoded = $encoded.Replace($key, $map[$key])
    }
    return $encoded
}

function Install-Dependencies {
    Write-Host 'Installing root dependencies...' -ForegroundColor Cyan
    pnpm install --prod --frozen-lockfile
    if ($LASTEXITCODE -ne 0) { throw "pnpm install failed at repo root (exit $LASTEXITCODE)" }

    Write-Host 'Installing backend dependencies...' -ForegroundColor Cyan
    Push-Location backend
    try {
        pnpm install --prod --frozen-lockfile
        if ($LASTEXITCODE -ne 0) { throw "pnpm install failed in backend (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }

    Write-Host 'Installing frontend dependencies...' -ForegroundColor Cyan
    Push-Location frontend
    try {
        pnpm install --prod --frozen-lockfile
        if ($LASTEXITCODE -ne 0) { throw "pnpm install failed in frontend (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
}

Write-Host '==========================================' -ForegroundColor Blue
Write-Host 'OpenShutter Production Setup (Windows)' -ForegroundColor Blue
Write-Host '==========================================' -ForegroundColor Blue
Write-Host ''

$isUpdate = Read-Default 'Is this an update to an existing installation? (y/n)' 'n'
if ($isUpdate -match '^[Yy]$') {
    Write-Host ''
    Write-Host 'Update mode: installing dependencies only (keeping existing .env files).' -ForegroundColor Yellow
    Write-Host ''
    Install-Dependencies
    Write-Host ''
    Write-Host 'Update completed successfully.' -ForegroundColor Green
    Write-Host 'Restart services: .\stop.ps1 (if running), then .\start.ps1' -ForegroundColor Yellow
    exit 0
}

Write-Host 'First installation: full setup' -ForegroundColor Green
Write-Host ''

$backendPort = Read-Default 'Backend port' '5000'
$frontendPort = Read-Default 'Frontend port' '4000'

Write-Host ''
Write-Host 'MongoDB configuration:' -ForegroundColor Cyan
$mongoHost = Read-Default 'MongoDB host' 'localhost:27017'
$mongoDb = Read-Default 'Database name' 'openshutter'
$mongoAuth = Read-Default 'Does MongoDB require authentication? (y/n)' 'n'

$mongoUri = "mongodb://${mongoHost}/${mongoDb}"
if ($mongoAuth -match '^[Yy]$') {
    $mongoUser = Read-Host 'MongoDB username'
    $mongoPass = Read-Host 'MongoDB password' -AsSecureString
    $mongoPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($mongoPass)
    )
    $mongoAuthSource = Read-Default 'MongoDB auth source' 'admin'
    $encodedPass = Encode-MongoPassword $mongoPassPlain
    $mongoUri = "mongodb://${mongoUser}:${encodedPass}@${mongoHost}/${mongoDb}?authSource=${mongoAuthSource}"
}

Write-Host ''
Write-Host 'Installing dependencies...' -ForegroundColor Cyan
Install-Dependencies

Write-Host ''
Write-Host 'Creating environment files...' -ForegroundColor Cyan

$jwtBytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($jwtBytes)
$jwtSecret = [Convert]::ToBase64String($jwtBytes)

@(
    '# MongoDB Configuration'
    "MONGODB_URI=$mongoUri"
    "MONGODB_DB=$mongoDb"
    ''
    '# Authentication Configuration'
    "AUTH_JWT_SECRET=$jwtSecret"
    ''
    '# Application Configuration'
    'NODE_ENV=production'
    "PORT=$backendPort"
    ''
    '# CORS Configuration'
    "FRONTEND_URL=http://localhost:$frontendPort"
) | Set-Content -Path 'backend\.env' -Encoding utf8

@(
    '# Authentication Configuration (SvelteKit)'
    "AUTH_JWT_SECRET=$jwtSecret"
    ''
    '# Application Configuration'
    'NODE_ENV=production'
    "BACKEND_URL=http://localhost:$backendPort"
    "PORT=$frontendPort"
    ''
    '# SvelteKit CSRF / cookie security — use http for local installs, https on real servers'
    "ORIGIN=http://localhost:$frontendPort"
) | Set-Content -Path 'frontend\.env.production' -Encoding utf8

$ecosystem = @"
// PM2 Ecosystem Configuration for OpenShutter Frontend
// Auto-generated by build.ps1 - do not edit manually

const fs = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '.env.production');
let envVars = {};

if (fs.existsSync(envPath)) {
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
}

module.exports = {
  apps: [{
    name: 'openshutter-frontend',
    script: 'build/index.js',
    cwd: __dirname,
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: $frontendPort,
      BACKEND_URL: 'http://localhost:$backendPort',
      AUTH_JWT_SECRET: '$jwtSecret',
      ...envVars
    },
    watch: false,
    max_memory_restart: '1G',
    restart_delay: 4000,
    min_uptime: '10s',
    max_restarts: 10,
    kill_timeout: 5000,
    wait_ready: true,
    listen_timeout: 10000,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true
  }]
};
"@
Set-Content -Path 'frontend\ecosystem.config.js' -Value $ecosystem -Encoding utf8

Write-Host ''
Write-Host 'Setup completed successfully.' -ForegroundColor Green
Write-Host "  Backend port:  $backendPort"
Write-Host "  Frontend port: $frontendPort"
Write-Host "  MongoDB URI:   $mongoUri"
Write-Host ''
Write-Host 'Files created:' -ForegroundColor Cyan
Write-Host '  backend\.env'
Write-Host '  frontend\.env.production'
Write-Host '  frontend\ecosystem.config.js'
Write-Host ''
Write-Host 'Start the app:  .\start.ps1' -ForegroundColor Yellow
Write-Host 'AUTH_JWT_SECRET is identical in backend and frontend env files.' -ForegroundColor Yellow
